test if file exists in send. abort if no exists.

diff --git a/orom/fs+bash/example/code/send b/orom/fs+bash/example/code/send
--- a/orom/fs+bash/example/code/send
+++ b/orom/fs+bash/example/code/send
@@ -7,6 +7,12 @@ recv=$1
 echo "send" > /dev/tty
 echo "-> test receiver $recv" > /dev/tty
 
+# If it doesn't exist, fail
+if [ ! -e $recv ]; then
+  echo " -> File does not exist, exiting..."
+  exit 1
+fi
+
 if [[ -L $recv ]]; then
   echo " -> Receiver is link for $recv" > /dev/tty
   recv=$(readlink -n $recv)
